### ISSUE TITLE
how to fetch more vulnerable sites? so far only few sites when i run ruby whitewidow.rb -d 

### ISSUE THREAD

**Issue by doxsec** [WhitewidowScanner/whitewidow#37]
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--

## Labels

 - [ ] Bug
 - [ ] Encoding
 - [ ] User agent
 - [ ] Enhancement
 - [x] Question
 - [ ] Email request

**Comment by Ekultek** [comment]
Not entirely sure what you mean? Whitewidow randomly selects a query from a file containing around 1500 queries. You can always specify your own using the -D flag

**Comment by Ekultek** [comment]
You could also always run the -x flag and specify an amount of times to run the program. Such as: ruby whitewidow.rb -x 10. Be careful with this though Google will block your searches after a certain amount, and I haven't figured out how to bypass the captcha without changing the IP address

**Comment by doxsec** [comment]
what i want is to be able to fetch more vulnerable results lets say scrape google and return say 200 sites to check for sqli so far i see it fetches just a few sites to check for sqli and also will you be adding more search engines in the future??

**Comment by Ekultek** [comment]
As of now there is no way of scraping more then the first page of Google results. Eventually there will be more search engines, but that's a work in progress. If you want more at a time use the -x flag
