### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by lianfeng30** [WhitewidowScanner/whitewidow#80]
mac run error
-------------------

all gem have installed

ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin16]
AAA:whitewidow AAA$ ls
Gemfile       README.md     lib           spec
Gemfile.lock  docs          log           whitewidow.rb
AAA:whitewidow AAA$ gem install mechanize
Successfully installed mechanize-2.7.5
Building YARD (yri) index for mechanize-2.7.5...
Done installing documentation for mechanize after 1 seconds
1 gem installed
AAA:whitewidow AAA$ ruby whitewidow.rb -h
/Users/AAA/whitewidow/lib/imports/constants_and_requires.rb:21:in `require_relative': /Users/AAA/whitewidow/lib/misc/legal.rb:13: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '(' (SyntaxError)
         [ LEGAL DISCLAIMER ]
                           ^
/Users/AAA/whitewidow/lib/misc/legal.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...d created for learning purposes only, I should
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
/Users/AAA/whitewidow/lib/misc/legal.rb:17: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...ork and what to look for so you don't become vulnerable, suc...
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:60: syntax error, unexpected tIDENTIFIER, expecting keyword_end
         come. Meaning if I'm approached by the authorities, I will
                             ^
/Users/AAA/whitewidow/lib/misc/legal.rb:60: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
/Users/AAA/whitewidow/lib/misc/legal.rb:66: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
         If for any reason you do not agree with the di...
                          ^
/Users/AAA/whitewidow/lib/misc/legal.rb:66: syntax error, unexpected keyword_or
...t agree with the disclaimer, or terms,
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:67: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
         please exit this program immediately, and remove it from your
                    ^
/Users/AAA/whitewidow/lib/misc/legal.rb:67: syntax error, unexpected keyword_and
         please exit this program immediately, and remove it from your
                                                  ^
/Users/AAA/whitewidow/lib/misc/legal.rb:70: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
... Having said that, knowledge is not illegal, nor is the will...
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:70: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...nowledge is not illegal, nor is the will to
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:81: syntax error, unexpected tCONSTANT, expecting keyword_end
         Press 'Enter' to continue..
                     ^
/Users/AAA/whitewidow/lib/misc/legal.rb:81: unterminated string meets end of file
/Users/AAA/whitewidow/lib/misc/legal.rb:81: syntax error, unexpected end-of-input, expecting keyword_end
	from /Users/AAA/whitewidow/lib/imports/constants_and_requires.rb:21:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'
AAA:whitewidow AAA$ sudo ruby whitewidow.rb -d
Password:
/Users/AAA/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mechanize (LoadError)
	from /Users/AAA/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/AAA/whitewidow/lib/imports/constants_and_requires.rb:3:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'
AAA:whitewidow AAA$ ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin16]
AAA:whitewidow AAA$ ruby whitewidow.rb --version
/Users/AAA/whitewidow/lib/imports/constants_and_requires.rb:21:in `require_relative': /Users/AAA/whitewidow/lib/misc/legal.rb:13: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '(' (SyntaxError)
         [ LEGAL DISCLAIMER ]
                           ^
/Users/AAA/whitewidow/lib/misc/legal.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...d created for learning purposes only, I should
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
/Users/AAA/whitewidow/lib/misc/legal.rb:17: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...ork and what to look for so you don't become vulnerable, suc...
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:60: syntax error, unexpected tIDENTIFIER, expecting keyword_end
         come. Meaning if I'm approached by the authorities, I will
                             ^
/Users/AAA/whitewidow/lib/misc/legal.rb:60: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
/Users/AAA/whitewidow/lib/misc/legal.rb:66: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
         If for any reason you do not agree with the di...
                          ^
/Users/AAA/whitewidow/lib/misc/legal.rb:66: syntax error, unexpected keyword_or
...t agree with the disclaimer, or terms,
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:67: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
         please exit this program immediately, and remove it from your
                    ^
/Users/AAA/whitewidow/lib/misc/legal.rb:67: syntax error, unexpected keyword_and
         please exit this program immediately, and remove it from your
                                                  ^
/Users/AAA/whitewidow/lib/misc/legal.rb:70: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
... Having said that, knowledge is not illegal, nor is the will...
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:70: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...nowledge is not illegal, nor is the will to
...                               ^
/Users/AAA/whitewidow/lib/misc/legal.rb:81: syntax error, unexpected tCONSTANT, expecting keyword_end
         Press 'Enter' to continue..
                     ^
/Users/AAA/whitewidow/lib/misc/legal.rb:81: unterminated string meets end of file
/Users/AAA/whitewidow/lib/misc/legal.rb:81: syntax error, unexpected end-of-input, expecting keyword_end
	from /Users/AAA/whitewidow/lib/imports/constants_and_requires.rb:21:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'

why? thanks

**Comment by Ekultek** [comment]
Update ruby
